# Librairies import

In [4]:
import numpy as np

# NumPy array
NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers

## 1D array

In [12]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print("ndim:", a.ndim)
print("shape :", a.shape)
print("size :", a.size)
print("dtype :", a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
ndim: 1
shape : (3,)
size : 3
dtype : int64


## 2D array

In [20]:
a = np.arange(15)
print(type(a))
print("ndim:", a.ndim)
print("shape :", a.shape)
print("size :", a.size)
print("dtype :", a.dtype)
a

<class 'numpy.ndarray'>
ndim: 1
shape : (15,)
size : 15
dtype : int64


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

An array can be reshape

In [22]:
b = a.reshape(3, 5)
print(type(b))
print("ndim:", b.ndim)
print("shape :", b.shape)
print("size :", b.size)
print("dtype :", b.dtype)
b

<class 'numpy.ndarray'>
ndim: 2
shape : (3, 5)
size : 15
dtype : int64


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Declaring arrays
They are several ways to create arrays

## From python list

In [39]:
a = np.array(['foo', 'bar'])
a

array(['foo', 'bar'], 
      dtype='<U3')

In [40]:
b = np.array([[1.3, -3.7], [7.6, -0.4]])
b

array([[ 1.3, -3.7],
       [ 7.6, -0.4]])

In [41]:
c = np.array( [ [1,2], [3,4] ], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

## With initial placeholded content

### Array full of zeros

In [42]:
np.zeros((4,7))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

### Array full of ones

In [38]:
np.ones((2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
dezadz

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])